### ISSUE TITLE
wiimote´s  intermittent dissconection

### ISSUE THREAD

**Issue by unnamedbot03** [simphax/Touchmote#107]
i´ve using touchmote since july of this year, and until now it worked really nice.
but 2 days ago, while connecting the wiimote connects, works a little while and then dissconect itself, almost at the same moment it also re connects and now it won't stop doing that. the connects also does not respond while desconecting and reconnecting.
what should i do?
i did check the drivers and also try in the wii if the wiimotes were broke or anything, but they were fine. so im asumming is a touchmote issue.
recommendations?
edit: i forgot to say that, but i also desinstalled and reinstalled.

**Comment by kleftangel** [comment]
Same issue. Connection with Wiimote to PC via Mayflash seems to work fine with dolphin emulator but as soon as touchmote is opened, connection problems start. Also tried to uninstall and then reinstall. Reinstalled drivers also. Issues may be related to a recent Windows update

**Comment by unnamedbot03** [comment]
i think is a problem related to pnp devices, but i didnt figure out yet.
i keep the research.

**Comment by kyzumi** [comment]
I just started using touchmote and I am having this issue. They disconnect and immedialy reconnect in a constant time frame. The reconnecting also seem to alternate between Remote 1 and Remote 2.

**Comment by Ryochan7** [comment]
Doesn't look like it is a problem with Touchmote. The actual problem is with the Steam client. Touchmote works fine until I open Steam and then it keeps disconnecting and reconnecting the Wiimote from my Dolphinbar. Steam BPM shows that is detects the Wiimote as **Generic Gamepad: Nintendo Wii Remote with Nunchuk** before the disconnect and then shows 4 controllers on the disconnect. Maybe the addition of Switch Pro and JoyCon support in Steam Input has something to do with it?

Either way, it looks like you need to hide the Wiimote from Steam using the HidHide driver. No problems after hiding the Wiimote from Steam.

https://github.com/ViGEm/HidHide

**Comment by unnamedbot03** [comment]
wow, thank you Ryochan!
it worked for me, i didnt download the drive, but i exit the steam.
so when ill use touchmote ill just exit steam.

**Comment by Sawtaytoes** [comment]
Correct. From my research, this is a recent issue with Steam. I sent a support request. I recommend you do too, or it'll probably never get fixed: https://help.steampowered.com/en/.

If they receive 8 or 9 requests for this one bug, I guarantee that'll push it up the priority list since we're a super niche minority of Steam users.

---

This issue happens to me even if Steam is closed. I can't physically see that the controller is connecting and disconnecting, but when I move the Nunchuck's joystick around in Cemu, it returns to center for a bit and stops responding to input, then it starts to move around again.
