### ISSUE TITLE
unable to pair on Windows 7

### ISSUE THREAD

**Issue by eadmaster** [simphax/Touchmote#43]
I've installed the latest Touchmote v1.0 beta 12 on Windows 7 Ultimate 64-bit (with SP1 and the default Microsoft bluetooth stack).
Pairing the wiimote doesn't work properly as it loops infinitely...
Do i need to install some 3rd party BT stack?

**Comment by eadmaster** [comment]
I've just tried on Windows10 with the same adapter and it worked at first try, so i guess the problem is the Win7 BT stack...

**Comment by eadmaster** [comment]
i've found a trick that seems to work with win7:
after pressing the "Pair Wiimotes" button, keep pressing repeatedly 1+2 on the wiimote until the pairing finishes.

**Comment by DasKatzchen** [comment]
I've found a better workaround. The problem is that, by default, Windows 7 will search Windows update for newer drivers EVERY time you connect a device.   This takes several minutes, and the wiimote times out.  In the 'hardware' tab of 'system properties' you can customize this behavior to only search when there aren't any local drivers. Might not help for the first time, but will definitely help all subsequent times.
